### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by ShafiMohammad09** [TammyAlok2/Hactoberfest2023_ADSC2#24]
hi there @TammyAlok2 👋
I've been exploring the project's <b>public/index.html </b>, and I noticed some areas where the UI design could be enhanced for a smoother user experience.

As a UI Designer and a Front-End Developer, I'd like to offer my assistance in improving it.

Would you be open to having me work on this task? I believe a more user-friendly interface could greatly benefit the project.

**Comment by TammyAlok2** [comment]
hello friend I want to inform you that  it is react based project so if you want to change then go through profile section for changes

**Comment by SAGARSINGH-1** [comment]
@TammyAlok2 If You have any design just give me I'll make it.

**Comment by TammyAlok2** [comment]
@ShafiMohammad09  Try to make this type of design if possible 
Iink: https://x.hellofaizan.me/

**Comment by SAGARSINGH-1** [comment]
Assign this issue to me

**Comment by ShafiMohammad09** [comment]
Sorry to interrupt brother,I appreciate your interest, but I've already been assigned to this task. However, there are other issues in the project that could benefit from your attention

**Comment by SAGARSINGH-1** [comment]
@ShafiMohammad09 Can you make that UI if yes then carry on if need help then maention I'll be there..

**Comment by ShafiMohammad09** [comment]
@SAGARSINGH-1 , thank you brother. I'll proceed with working on the UI. If I encounter any challenges, I'll definitely reach out for your assistance. Appreciate your support!"

**Comment by TammyAlok2** [comment]
sure @ShafiMohammad09  I will if you don't have enough information of react but you know the css my suggestion is to talk to @SAGARSINGH-1  he also help you as we know this is open source contribution 
we need best ui design 
Hope you understand

**Comment by SAGARSINGH-1** [comment]
yes @ShafiMohammad09 if You dosen't have good knowledge in React tell me I'll create it and You just give CSS to them if you want

**Comment by ShafiMohammad09** [comment]
"Alright, I'm eager to be part of the project. This presents an opportunity for me to learn something new. Please ensure to let me apply the CSS so I can make a meaningful contribution to the project."

**Comment by SAGARSINGH-1** [comment]
@TammyAlok2 merge this PR to contribute in CSS by @ShafiMohammad09

**Comment by SAGARSINGH-1** [comment]
@TammyAlok2 please don't close this issue its not completed yet.

**Comment by SAGARSINGH-1** [comment]
hey @ShafiMohammad09 Add CSS in both Components for Header/Navigation add CSS in Header.css file and for Profile component add CSS in Profile.css file.
