### ISSUE TITLE
Add CONTRIBUTORS section in README.md

### ISSUE THREAD

**Issue by Vani177** [TammyAlok2/Hactoberfest2023_ADSC2#6]
Hey!
I'd like to improvise readme.md by adding the contributors section.
Please consider assigning me this issue.
Thanks :)

**Comment by Vani177** [comment]
thanks for assigning me this issue, i'll make sure to finish it by tomorrow, to make it count in the contributions for hactoberfest :)

**Comment by trapti77** [comment]
Hey ,
I want to improve readme.md file by Add contributors list to Readme file.
